// src/events/events.ts
export const EVENTS = {
  USER_CREATED: "user.created",
  TRANSACTION_COMPLETED: "transaction.completed",
  TRANSACTION_CREATED: "transaction.created",
  TRANSACTION_FAILED: "transaction.failed",
  TRANSACTION_DELETED: "transaction.deleted",
  TRANSACTION_UPDATED: "transaction.updated",
  PAYMENT_FAILED: "payment.failed",
  PAYMENT_UPDATED: "payment.updated",
  PAYMENT_CREATED: "payment.created",
  PAYMENT_REVERSED: "payment.reversed",
  PAYMENT_REFUNDED: "payment.refunded",
  PAYMENT_DELETED: "payment.deleted",
  STOCK_MOVEMENT_CREATED: "stockMovement.created",
  STOCK_MOVEMENT_UPDATED: "stockMovement.updated",
  STOCK_MOVEMENT_REMOVED: "stockMovement.removed",
  STOCK_EXPIRY_PROCESSED: "stock.expiryProcessed",
  PURCHASE_ORDER_CREATED: "purchaseOrder.created",
  PURCHASE_ORDER_UPDATED: "purchaseOrder.updated",
  PURCHASE_ORDER_INVOICED: "purchaseOrder.invoiced",
  PURCHASE_ORDER_RECEIVED: "purchaseOrder.received",
  PURCHASE_ORDER_CANCELLED: "purchaseOrder.cancelled",
  PURCHASE_ORDER_APPROVED: "purchaseOrder.approved",
  PURCHASE_ORDER_SHIPPED: "purchaseOrder.shipped",
  PURCHASE_ORDER_DELIVERED: "purchaseOrder.delivered",
  PURCHASE_ORDER_RETURNED: "purchaseOrder.returned",
  PURCHASE_ORDER_REFUNDED: "purchaseOrder.refunded",
  TENANT_CREATED: "tenant.created",
  TENANT_UPDATED: "tenant.updated",
  TENANT_DELETED: "tenant.deleted",
  B2B_CONNECTION_CREATED: "b2bConnection.created",
  B2B_CONNECTION_UPDATED: "b2bConnection.updated",
  B2B_CONNECTION_DELETED: "b2bConnection.deleted",
  B2B_CONNECTION_APPROVED: "b2bConnection.approved",
  B2B_CONNECTION_REJECTED: "b2bConnection.rejected",
  B2B_CONNECTION_REVOKED: "b2bConnection.revoked",
  B2B_CONNECTION_SYNCED: "b2bConnection.synced",
  B2B_CONNECTION_SYNC_FAILED: "b2bConnection.syncFailed",
  TENANT_NOT_FOUND: "tenant.notFound",
  TENANT_EXISTS: "tenant.exists",
  INVALID_STATUS_CHANGE: "invalidStatusChange",
  PRODUCT_CATEGORY_CREATED: "product_category.created",
  PRODUCT_CREATED: "product.created",
  PRODUCT_CATEGORY_UPDATED: "product_category.updated",
  PRODUCT_CATEGORY_DELETED: "product_category.deleted",
  PRODUCT_VARIANT_CREATED: "product_variant.created",
  PRODUCT_VARIANT_UPDATED: "product_variant.updated",
  PRODUCT_VARIANT_DELETED: "product_variant.deleted",
  PRODUCT_UPDATED: "product.updated",
  PRODUCT_DELETED: "product.deleted",
  ORDER_CREATED: "order.created",
  ORDER_UPDATED: "order.updated",
  ORDER_DELETED: "order.deleted",
  STOCK_UPDATED: "stock.updated",
  STOCK_LEVEL_UPDATED: "stockLevel.updated",
  STOCK_DELETED: "stock.deleted",
  STOCK_ADJUSTED: "stock.adjusted",
  STOCK_RELEASED: "stock.released",
  STOCK_RESERVED: "stock.reserved",
  INVENTORY_MOVEMENT_CREATED: "inventory_movement.created",
  INVENTORY_MOVEMENT_UPDATED: "inventory_movement.updated",
  INVENTORY_MOVEMENT_VOIDED: "inventory_movement.voided",
  INVENTORY_MOVEMENT_DELETED: "inventory_movement.deleted",
  INVENTORY_CONSUMED: "inventory.consumed",
  INVENTORY_RECEIPT_FROM_PO: "inventory.receiptFromPo",
  STOCK_TRANSFER_REQUESTED: "stockTransfer.requested",
  STOCK_TRANSFER_REJECTED: "stockTransfer.rejected",
  STOCK_TRANSFER_APPROVED: "stockTransfer.approved",
  STOCK_TRANSFER_UPDATED: "stockTransfer.updated",
  STOCK_TRANSFER_COMPLETED: "stockTransfer.completed",
  STOCK_TRANSFER_RECEIPT_RECORDED: "stockTransfer.receipt_recorded ",
  STOCK_TRANSFER_CANCELLED: "stockTransfer.cancelled",
  PURCHASE_ORDER_PAYMENT_LINKED: "purchaseOrder.paymentLinked",
  POS_SESSION_OPENED: "posSession.opened",
  POS_SESSION_CLOSED: "posSession.closed",
  POS_ORDER_CREATED: "posOrder.created",
  POS_SESSION_UPDATED: "posSession.updated",
  POS_ITEM_ADDED: "posItem.added",
  POS_ITEM_UPDATED: "posItem.updated",
  POS_ITEM_REMOVED: "posItem.removed",
  POS_CASH_DROP_CREATED: "posCashDrop.created",
  POS_SALES_RETURN_CREATED: "posSalesReturn.created",
  POS_TRANSACTION_CREATED: "posTransaction.created",
  POS_RETURN_CREATED: "posReturn.created",
  POS_CASH_DROP: "posCashDrop.created",
  POS_SALE_COMPLETED: "posSale.completed",
  POS_PAYMENT_CREATED: "posPayment.created",
  POS_RECEIPT_READY: "posReceipt.ready",
  POS_RECONCILIATION_CREATED: "posReconciliation.created",
  REPORT_GENERATED: "report.generated",
  INVOICE_CREATED: "invoice.created",
  INVOICE_OVERDUE: "invoice.overdue",
  INVOICE_UPDATED: "invoice.updated",
  INVOICE_PAID: "invoice.paid",
  INVOICE_VOIDED: "invoice.voided",
  INVOICE_REFUNDED: "invoice.refunded",
  INVOICE_DELETED: "invoice.deleted",
  INVOICE_ISSUED: "invoice.issued",
  INVOICE_PAYMENT_APPLIED: "invoice.paymentApplied",
  INVOICE_PDF_GENERATED: "invoice.pdfGenerated",
  GLOBAL_PRODUCT_CREATED: "globalCatalog.created",
  GLOBAL_PRODUCT_DELETED: "globalCatalog.deleted",
  GLOBAL_PRODUCT_UPDATED: "globalCatalog.updated",
  GLOBAL_PRODUCT_CATEGORY_CREATED: "globalCatalogCategory.created",
  GLOBAL_PRODUCT_CATEGORY_UPDATED: "globalCatalogCategory.updated",
  GLOBAL_PRODUCT_CATEGORY_DELETED: "globalCatalogCategory.deleted",
  GLOBAL_PRODUCT_VARIANT_CREATED: "globalCatalogVariant.created",
  GLOBAL_PRODUCT_VARIANT_UPDATED: "globalCatalogVariant.updated",
  GLOBAL_PRODUCT_VARIANT_DELETED: "globalCatalogVariant.deleted",
  GLOBAL_PRODUCT_SEARCH_REQUESTED: "globalCatalog.searchRequested",
  GLOBAL_CATEGORY_CREATED: "globalCategory.created",
  GLOBAL_CATEGORY_UPDATED: "globalCategory.updated",
  GLOBAL_CATEGORY_DELETED: "globalCategory.deleted",
  GLOBAL_CATEGORY_SEARCH_REQUESTED: "globalCategory.searchRequested",
  GLOBAL_VARIANT_CREATED: "globalVariant.created",
  GLOBAL_VARIANT_UPDATED: "globalVariant.updated",
  TENANT_PRODUCT_CREATED: "tenantProduct.created",
  TENANT_PRODUCT_UPDATED: "tenantProduct.updated",
  TENANT_PRODUCT_DELETED: "tenantProduct.deleted",
  TENANT_PRODUCT_SEARCH_REQUESTED: "tenantProduct.searchRequested",
  TENANT_CATEGORY_CREATED: "tenantCategory.created",
  TENANT_CATEGORY_UPDATED: "tenantCategory.updated",
  TENANT_CATEGORY_DELETED: "tenantCategory.deleted",
  TENANT_CATEGORY_SEARCH_REQUESTED: "tenantCategory.searchRequested",
  TENANT_VARIANT_CREATED: "tenantVariant.created",
  TENANT_VARIANT_UPDATED: "tenantVariant.updated",
  TENANT_VARIANT_DELETED: "tenantVariant.deleted",
  GLOBAL_VARIANT_DELETED: "globalVariant.deleted",
  






  // … more user events …

  // … more transaction events …
  // … more domain events …
};
