    # --- Product Schemas ---
    CreateProductDto:
      type: object
      required:
        - name
        - sku
        - tenantId
        - costPrice
        - sellingPrice
      properties:
        tenantId:
          type: string
          description: Tenant ID
        categoryId:
          type: string
          description: Category ID (optional)
        name:
          type: string
          minLength: 2
          example: "Paracetamol 500mg"
        sku:
          type: string
          minLength: 2
          example: "PARA-500"
        barcode:
          type: string
          example: "123456789012"
        description:
          type: string
          example: "Pain reliever and fever reducer"
        brand:
          type: string
          example: "Generic"
        costPrice:
          type: number
          minimum: 0
          example: 5.99
        sellingPrice:
          type: number
          minimum: 0
          example: 9.99
        isActive:
          type: boolean
          default: true
        dosageForm:
          type: string
          example: "tablet"
        strength:
          type: string
          example: "500mg"
        variants:
          type: array
          items:
            $ref: '#/components/schemas/CreateProductVariantDto'

    Product:
      allOf:
        - $ref: '#/components/schemas/CreateProductDto'
        - type: object
          properties:
            id:
              type: string
            createdAt:
              type: string
              format: date-time
            updatedAt:
              type: string
              format: date-time
            category:
              $ref: '#/components/schemas/ProductCategory'
            variants:
              type: array
              items:
                $ref: '#/components/schemas/ProductVariant'

    ProductVariant:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
          example: "100 tablets bottle"
        sku:
          type: string
          example: "PARA-500-100TAB"
        costPrice:
          type: number
        sellingPrice:
          type: number
        isActive:
          type: boolean
        createdAt:
          type: string
          format: date-time

    ProductCategory:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
          example: "Analgesics"
        description:
          type: string
          example: "Pain relief medications"
        createdAt:
          type: string
          format: date-time

    Pagination:
      type: object
      properties:
        total:
          type: integer
        page:
          type: integer
        limit:
          type: integer
        totalPages:
          type: integer